package com.deemsys.project.entity;

// Generated 5 Apr, 2017 1:14:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CheckerUploaderMappingId generated by hbm2java
 */
@Embeddable
public class CheckerUploaderMappingId implements java.io.Serializable {

	private String uploaderAccountId;
	private String checkerAccountId;

	public CheckerUploaderMappingId() {
	}

	public CheckerUploaderMappingId(String uploaderAccountId,
			String checkerAccountId) {
		this.uploaderAccountId = uploaderAccountId;
		this.checkerAccountId = checkerAccountId;
	}

	@Column(name = "uploader_account_id", nullable = false, length = 32)
	public String getUploaderAccountId() {
		return this.uploaderAccountId;
	}

	public void setUploaderAccountId(String uploaderAccountId) {
		this.uploaderAccountId = uploaderAccountId;
	}

	@Column(name = "checker_account_id", nullable = false, length = 32)
	public String getCheckerAccountId() {
		return this.checkerAccountId;
	}

	public void setCheckerAccountId(String checkerAccountId) {
		this.checkerAccountId = checkerAccountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CheckerUploaderMappingId))
			return false;
		CheckerUploaderMappingId castOther = (CheckerUploaderMappingId) other;

		return ((this.getUploaderAccountId() == castOther
				.getUploaderAccountId()) || (this.getUploaderAccountId() != null
				&& castOther.getUploaderAccountId() != null && this
				.getUploaderAccountId()
				.equals(castOther.getUploaderAccountId())))
				&& ((this.getCheckerAccountId() == castOther
						.getCheckerAccountId()) || (this.getCheckerAccountId() != null
						&& castOther.getCheckerAccountId() != null && this
						.getCheckerAccountId().equals(
								castOther.getCheckerAccountId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUploaderAccountId() == null ? 0 : this
						.getUploaderAccountId().hashCode());
		result = 37
				* result
				+ (getCheckerAccountId() == null ? 0 : this
						.getCheckerAccountId().hashCode());
		return result;
	}

}
