package com.deemsys.project.entity;

// Generated 21 Mar, 2017 1:18:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrashReports generated by hbm2java
 */
@Entity
@Table(name = "crash_reports", catalog = "CRM")
public class CrashReports implements java.io.Serializable {

	private String reportId;
	private Accounts accounts;
	private County county;
	private String reportNumber;
	private Date crashDate;
	private String location;
	private Integer noOfOccupants;
	private String fileName;
	private Date addedDate;
	private Date addedDateTime;
	private Integer status;
	private Set<Occupants> occupantses = new HashSet<Occupants>(0);

	public CrashReports() {
	}

	public CrashReports(String reportId) {
		this.reportId = reportId;
	}

	public CrashReports(String reportId, Accounts accounts, County county,
			String reportNumber, Date crashDate, String location,
			Integer noOfOccupants, String fileName, Date addedDate,
			Date addedDateTime, Integer status, Set<Occupants> occupantses) {
		this.reportId = reportId;
		this.accounts = accounts;
		this.county = county;
		this.reportNumber = reportNumber;
		this.crashDate = crashDate;
		this.location = location;
		this.noOfOccupants = noOfOccupants;
		this.fileName = fileName;
		this.addedDate = addedDate;
		this.addedDateTime = addedDateTime;
		this.status = status;
		this.occupantses = occupantses;
	}

	@Id
	@Column(name = "report_id", unique = true, nullable = false, length = 32)
	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "county_id")
	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	@Column(name = "report_number", length = 100)
	public String getReportNumber() {
		return this.reportNumber;
	}

	public void setReportNumber(String reportNumber) {
		this.reportNumber = reportNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "crash_date", length = 10)
	public Date getCrashDate() {
		return this.crashDate;
	}

	public void setCrashDate(Date crashDate) {
		this.crashDate = crashDate;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "no_of_occupants")
	public Integer getNoOfOccupants() {
		return this.noOfOccupants;
	}

	public void setNoOfOccupants(Integer noOfOccupants) {
		this.noOfOccupants = noOfOccupants;
	}

	@Column(name = "file_name", length = 250)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 10)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "added_date_time", length = 19)
	public Date getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(Date addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crashReports")
	public Set<Occupants> getOccupantses() {
		return this.occupantses;
	}

	public void setOccupantses(Set<Occupants> occupantses) {
		this.occupantses = occupantses;
	}

}
