package com.deemsys.project.entity;

// Generated 5 Apr, 2017 1:14:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrashReports generated by hbm2java
 */
@Entity
@Table(name = "crash_reports", catalog = "CRM")
public class CrashReports implements java.io.Serializable {

	private String reportId;
	private Accounts accountsByVerifyAccountId;
	private Accounts accountsByAccountId;
	private County county;
	private String reportNumber;
	private Date crashDate;
	private String location;
	private Integer crashSeverity;
	private Integer noOfOccupants;
	private String fileName;
	private Date addedDate;
	private Date addedDateTime;
	private Integer verifiedStatus;
	private Integer status;
	private Set<VerificationLog> verificationLogs = new HashSet<VerificationLog>(
			0);
	private Set<Occupants> occupantses = new HashSet<Occupants>(0);

	public CrashReports() {
	}

	public CrashReports(String reportId) {
		this.reportId = reportId;
	}

	public CrashReports(String reportId, Accounts accountsByVerifyAccountId,
			Accounts accountsByAccountId, County county, String reportNumber,
			Date crashDate, String location, Integer crashSeverity,
			Integer noOfOccupants, String fileName, Date addedDate,
			Date addedDateTime, Integer verifiedStatus, Integer status,
			Set<VerificationLog> verificationLogs, Set<Occupants> occupantses) {
		this.reportId = reportId;
		this.accountsByVerifyAccountId = accountsByVerifyAccountId;
		this.accountsByAccountId = accountsByAccountId;
		this.county = county;
		this.reportNumber = reportNumber;
		this.crashDate = crashDate;
		this.location = location;
		this.crashSeverity = crashSeverity;
		this.noOfOccupants = noOfOccupants;
		this.fileName = fileName;
		this.addedDate = addedDate;
		this.addedDateTime = addedDateTime;
		this.verifiedStatus = verifiedStatus;
		this.status = status;
		this.verificationLogs = verificationLogs;
		this.occupantses = occupantses;
	}

	@Id
	@Column(name = "report_id", unique = true, nullable = false, length = 32)
	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "verify_account_id")
	public Accounts getAccountsByVerifyAccountId() {
		return this.accountsByVerifyAccountId;
	}

	public void setAccountsByVerifyAccountId(Accounts accountsByVerifyAccountId) {
		this.accountsByVerifyAccountId = accountsByVerifyAccountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Accounts getAccountsByAccountId() {
		return this.accountsByAccountId;
	}

	public void setAccountsByAccountId(Accounts accountsByAccountId) {
		this.accountsByAccountId = accountsByAccountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "county_id")
	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	@Column(name = "report_number", length = 100)
	public String getReportNumber() {
		return this.reportNumber;
	}

	public void setReportNumber(String reportNumber) {
		this.reportNumber = reportNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "crash_date", length = 10)
	public Date getCrashDate() {
		return this.crashDate;
	}

	public void setCrashDate(Date crashDate) {
		this.crashDate = crashDate;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "crash_severity")
	public Integer getCrashSeverity() {
		return this.crashSeverity;
	}

	public void setCrashSeverity(Integer crashSeverity) {
		this.crashSeverity = crashSeverity;
	}

	@Column(name = "no_of_occupants")
	public Integer getNoOfOccupants() {
		return this.noOfOccupants;
	}

	public void setNoOfOccupants(Integer noOfOccupants) {
		this.noOfOccupants = noOfOccupants;
	}

	@Column(name = "file_name", length = 250)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 10)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "added_date_time", length = 19)
	public Date getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(Date addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "verified_status")
	public Integer getVerifiedStatus() {
		return this.verifiedStatus;
	}

	public void setVerifiedStatus(Integer verifiedStatus) {
		this.verifiedStatus = verifiedStatus;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crashReports")
	public Set<VerificationLog> getVerificationLogs() {
		return this.verificationLogs;
	}

	public void setVerificationLogs(Set<VerificationLog> verificationLogs) {
		this.verificationLogs = verificationLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crashReports")
	public Set<Occupants> getOccupantses() {
		return this.occupantses;
	}

	public void setOccupantses(Set<Occupants> occupantses) {
		this.occupantses = occupantses;
	}

}
