package com.deemsys.project.entity;

// Generated 29 Apr, 2017 1:50:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PoliceDepartment generated by hbm2java
 */
@Entity
@Table(name = "police_department", catalog = "CRM_boardman")
public class PoliceDepartment implements java.io.Serializable {

	private Integer policeDepartmentId;
	private String name;
	private String code;
	private Date createdDateTime;
	private Integer status;
	private Set<Accounts> accountses = new HashSet<Accounts>(0);
	private Set<CrashReports> crashReportses = new HashSet<CrashReports>(0);

	public PoliceDepartment() {
	}

	public PoliceDepartment(String name, String code, Date createdDateTime, Integer status,
			Set<Accounts> accountses, Set<CrashReports> crashReportses) {
		this.name = name;
		this.code = code;
		this.status = status;
		this.createdDateTime = createdDateTime;
		this.accountses = accountses;
		this.crashReportses = crashReportses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "police_department_id", unique = true, nullable = false)
	public Integer getPoliceDepartmentId() {
		return this.policeDepartmentId;
	}

	public void setPoliceDepartmentId(Integer policeDepartmentId) {
		this.policeDepartmentId = policeDepartmentId;
	}

	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "created_date_time")
	public Date getCreatedDateTime() {
		return createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policeDepartment")
	public Set<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set<Accounts> accountses) {
		this.accountses = accountses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policeDepartment")
	public Set<CrashReports> getCrashReportses() {
		return this.crashReportses;
	}

	public void setCrashReportses(Set<CrashReports> crashReportses) {
		this.crashReportses = crashReportses;
	}

}
