package com.deemsys.project.entity;
// Generated Jul 26, 2017 1:16:07 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name = "settings", catalog = "CRM_boardman")
public class Settings implements java.io.Serializable {

	private Integer settingId;
	private String settingKey;
	private String settingValue;

	public Settings() {
	}

	public Settings(String settingKey, String settingValue) {
		this.settingKey = settingKey;
		this.settingValue = settingValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "setting_id", unique = true, nullable = false)
	public Integer getSettingId() {
		return this.settingId;
	}

	public void setSettingId(Integer settingId) {
		this.settingId = settingId;
	}

	@Column(name = "setting_key", length = 100)
	public String getSettingKey() {
		return this.settingKey;
	}

	public void setSettingKey(String settingKey) {
		this.settingKey = settingKey;
	}

	@Column(name = "setting_value", length = 100)
	public String getSettingValue() {
		return this.settingValue;
	}

	public void setSettingValue(String settingValue) {
		this.settingValue = settingValue;
	}

}
