package com.deemsys.project.entity;

// Generated 5 Apr, 2017 1:14:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VerificationLog generated by hbm2java
 */
@Entity
@Table(name = "verification_log", catalog = "CRM")
public class VerificationLog implements java.io.Serializable {

	private Long verificationLogId;
	private Accounts accounts;
	private CrashReports crashReports;
	private String verifiedNotes;
	private Date verifiedDateTime;
	private Integer verifiedStatus;
	private Integer status;

	public VerificationLog() {
	}

	public VerificationLog(Accounts accounts, CrashReports crashReports,
			String verifiedNotes, Date verifiedDateTime,
			Integer verifiedStatus, Integer status) {
		this.accounts = accounts;
		this.crashReports = crashReports;
		this.verifiedNotes = verifiedNotes;
		this.verifiedDateTime = verifiedDateTime;
		this.verifiedStatus = verifiedStatus;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "verification_log_id", unique = true, nullable = false)
	public Long getVerificationLogId() {
		return this.verificationLogId;
	}

	public void setVerificationLogId(Long verificationLogId) {
		this.verificationLogId = verificationLogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "verified_by")
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "report_id")
	public CrashReports getCrashReports() {
		return this.crashReports;
	}

	public void setCrashReports(CrashReports crashReports) {
		this.crashReports = crashReports;
	}

	@Column(name = "verified_notes")
	public String getVerifiedNotes() {
		return this.verifiedNotes;
	}

	public void setVerifiedNotes(String verifiedNotes) {
		this.verifiedNotes = verifiedNotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "verified_date_time", length = 19)
	public Date getVerifiedDateTime() {
		return this.verifiedDateTime;
	}

	public void setVerifiedDateTime(Date verifiedDateTime) {
		this.verifiedDateTime = verifiedDateTime;
	}

	@Column(name = "verified_status")
	public Integer getVerifiedStatus() {
		return this.verifiedStatus;
	}

	public void setVerifiedStatus(Integer verifiedStatus) {
		this.verifiedStatus = verifiedStatus;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
